version: '3.9'
networks:
  dev:
    driver: 'bridge'
    
services:
  employeelog.api:
    image: employeelog
    depends_on: 
      - "app_db"
    container_name: employeelog-api
    ports:
      - "8088:80"
    build:
      context: .
      dockerfile: EmployeeLog.Api/Dockerfile
    restart: always
    environment: 
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev

  app_db:
    image: postgres:latest
    container_name: app_db
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=superSecret
      - POSTGRES_DB=EmployeeLogDb
    ports:
      - 5433:5432
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  app_data:
      